# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FileService Lambda CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Create env file
      run: |
        touch .env
        echo AWS_REGION=${{ secrets.AWS_REGION }} >> .env
        echo BUCKET_NAME=${{ secrets.BUCKET_NAME }} >> .env
        ls -la
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: Generate deployment package
      run: zip -r deploy.zip * -x '*.git*'
    
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@v0.1.5
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: file-service
          zip_file: deploy.zip

